version: "3.8"

services:
  postgres:
    image: postgres:16.2
    ports:
      - "8000:5432"
    environment:
      POSTGRES_DB: ogms_gateway
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - gateway_db:/var/lib/postgresql/data

volumes:
  gateway_db: