version: "3.8"

services:
  db:
    image: postgres:16.2
    ports:
      - "8001:5432"
    environment:
      POSTGRES_DB: ogms_products
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - product_db:/var/lib/postgresql/data

volumes:
  product_db: