version: "3.8"

services:
  orderapp:
    build: .
    ports:
      - "9003:9003"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://orderdb:5432
      SPRING_DATASOURCE_NAME: ogms_orders
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - orderdb
    networks:
      - ogms
  orderdb:
    image: postgres:16.2
    environment:
      POSTGRES_DB: ogms_orders
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - orders_db:/var/lib/postgresql/data
      - ./resources/db/orders_init.sql:/docker-entrypoint-initdb.d/orders_init.sql
    networks:
      - ogms

volumes:
  orders_db:

networks:
  ogms:
    name: ogms