version: "3.8"

services:
  orderapp:
    build: .
    ports:
      - "8081:8081"
    environment:
      OGMS_GATEWAY_URL: http://gatewayapp:9000
    networks:
      - ogms

networks:
  ogms:
    name: ogms