version: "3.8"

services:
  cartapp:
    build: .
    ports:
      - "9002:9002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cartdb:5432
      SPRING_DATASOURCE_NAME: ogms_cart
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - cartdb
    networks:
      - ogms
  cartdb:
    image: postgres:16.2
    environment:
      POSTGRES_DB: ogms_cart
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - cart_db:/var/lib/postgresql/data
      - ./resources/db/cart_init.sql:/docker-entrypoint-initdb.d/cart_init.sql
    networks:
      - ogms

volumes:
  cart_db:

networks:
  ogms:
    name: ogms